### PR TITLE
Allow substitute epsilon for Cholesky decomp

### PR DESCRIPTION
**Pull request by Fuuzetsu**
See #43 for details.

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
Oh, I didn't have my remote up to date. Let me resolve the conflicts...

**Comment by Fuuzetsu** [comment]
Rebased.

**Comment by nestordemeure** [comment]
I added some comments, mostly small changes to the documentation and comments. I will merge once they are taken into account.

I will release an updated version to crates.io soon after this and the other PR are merged.

**Review by nestordemeure — CHANGES_REQUESTED** [review]
Sorry, here are the comments!

**Comment by Fuuzetsu** [comment]
> Sorry, here are the comments!

Addressed. I must have marked the GitHub notification as done or something because I missed it, sorry for the delay.

If it's just small stuff, you're most welcome to edit the commits and/or merge then fix it up to your liking rather than waiting for me!

PTAL

**Review by nestordemeure — APPROVED** [review]

**Pull request merged**
